/**
 * Conformance against the reference implementation.
 *
 * The FSRS equations are short enough to look obviously right and subtle
 * enough to be quietly wrong — a clamp at the wrong bound, a missing exponent,
 * a baseline that should not have been clamped. Reading the formulas next to
 * the paper does not catch those. Running the same inputs through someone
 * else's implementation does.
 *
 * `fixtures/ts-fsrs-reference.json` holds 244 (memory, elapsed, grade) →
 * (stability, difficulty) triples generated by `ts-fsrs` v5.4.2 (FSRS-6.0,
 * MIT, github.com/open-spaced-repetition/ts-fsrs) via its `FSRSAlgorithm
 * .next_state`, plus forgetting-curve samples. If this file goes red, this
 * package has diverged from the algorithm it claims to implement.
 *
 * To regenerate after an upstream release:
 *
 *   npm i ts-fsrs && node -e "..."   // see the fixture's `version` field
 *
 * Tolerance is 1e-6 rather than exact: the reference rounds to 8 decimals
 * after every intermediate step and this package does not, so the two drift
 * in the last few digits and agree everywhere that matters.
 */

import {
  DEFAULT_FSRS_CONFIG,
  FSRS_6_DEFAULT_WEIGHTS,
  applyFSRS,
  retrievability,
} from '../src/index';
import type { FSRSRating, MemoryState } from '../src/index';
import reference from './fixtures/ts-fsrs-reference.json';

type Case = {
  memory: MemoryState | null;
  t: number;
  g: number;
  next: { stability: number; difficulty: number };
};

const config = { ...DEFAULT_FSRS_CONFIG, weights: FSRS_6_DEFAULT_WEIGHTS };
const TOLERANCE = 1e-6;

/**
 * Relative, not absolute. The reference rounds the retrievability it feeds
 * into the stability formulas to 8 decimals; that rounding then runs through
 * an exponential, so on a card with stability in the thousands the two
 * implementations differ by ~1e-5 in absolute terms and ~1e-8 in relative
 * ones. The relative figure is the one that says whether the formula matches.
 */
function relativeError(actual: number, expected: number): number {
  return Math.abs(actual - expected) / Math.max(Math.abs(expected), 1);
}

describe(`conformance with ts-fsrs ${reference.version}`, () => {
  it('uses the same FSRS-6 default weights', () => {
    expect(Array.from(FSRS_6_DEFAULT_WEIGHTS)).toEqual(reference.w);
  });

  it('reproduces the reference forgetting curve', () => {
    for (const point of reference.curve) {
      expect(retrievability(point.t, point.S, FSRS_6_DEFAULT_WEIGHTS)).toBeCloseTo(
        point.r,
        6,
      );
    }
  });

  it.each(reference.cases as Case[])(
    'next_state(S=$memory.stability, D=$memory.difficulty, t=$t, g=$g)',
    ({ memory, t, g, next }) => {
      const actual = applyFSRS(memory, g as FSRSRating, t, config);

      expect(relativeError(actual.stability, next.stability)).toBeLessThan(TOLERANCE);
      expect(relativeError(actual.difficulty, next.difficulty)).toBeLessThan(TOLERANCE);
    },
  );
});
